/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateNamedPipeApp */

#ifndef _Included_CreateNamedPipeApp
#define _Included_CreateNamedPipeApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CreateNamedPipeApp
 * Method:    createNamedPipe
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CreateNamedPipeApp_createNamedPipe
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
