/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniPosixSpawn */

#ifndef _Included_JniPosixSpawn
#define _Included_JniPosixSpawn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniPosixSpawn
 * Method:    callC
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JniPosixSpawn_callC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
